evan.edj: SmartInput.edc SmartInput.js SmartListH.edc SmartListV.edc SmartList.js SmartKB.edc SmartKB.js Makefile
	/usr/devel/bin/edje_cc -v -id images evan.edc evan.edj
	/usr/devel/bin/eet -i evan.edj "Evan_Input" SmartInput.js 1
	/usr/devel/bin/eet -i evan.edj "Evan_List" SmartList.js 1
	/usr/devel/bin/eet -i evan.edj "Evan_Keyboard" SmartKB.js 1
	